/*
1.    Usted es el administrador de la base de datos Northwind. 
Su cuenta Windows está formada por la inicial de su nombre 
y su apellido. Como administrador de Northwind solo tiene acceso
a la metadata, pudiendo crear objetos en la base de datos según 
las indicaciones del diseñador de la aplicación. No puede 
consultar los datos.
*/
USE [master]
GO
CREATE LOGIN [GMARQUEZ] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [GMARQUEZ]
GO
USE [master]
GO
CREATE USER [GMARQUEZ] FOR LOGIN [GMARQUEZ]
GO

/*
2.    ANDREW FULLER (AFULLER) ES EL VICEPRESIDENTE,
Y ADEMÁS ADMINISTRA DIRECTAMENTE LAS VENTAS CORPORATIVAS,
POR LO QUE PUEDE EFECTUAR TAREAS DE MANTENIMIENTO DE EMPLEADOS.
TAMBIÉN NECESITA OBTENER INFORMACIÓN ACERCA DE LOS PEDIDOS,
PERO ÉL NO SE ENCARGA DE INGRESAR LOS PEDIDOS AL SISTEMA.
*/

USE [NORTHWIND]
GO

CREATE LOGIN [AFULLER] WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND], DEFAULT_LANGUAGE=[ESPAÑOL],
CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO


CREATE USER [AFULLER] FOR LOGIN [AFULLER]
GO

GRANT SELECT ON EMPLOYEES TO AFULLER
GO

GRANT UPDATE ON EMPLOYEES TO AFULLER
GO

/*
3.    JANET LEVERLING (JLEVERLING) Y MARGARET PEACOCK (MPEACOCK)
 SON VENDEDORES CORPORATIVOS,  REPORTAN A ANDREW FULLER,
  Y DEBEN REGISTRAR SUS PEDIDOS EN EL SISTEMA;
  TAMBIÉN PUEDEN EVENTUALMENTE ELIMINAR PEDIDOS
  Ó CORREGIR ALGÚN DATO DE LOS MISMOS.
  */


CREATE LOGIN [JLEVERLING] WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [NORTHWIND]
GO
CREATE USER [JLEVERLING] FOR LOGIN [JLEVERLING]
GO

CREATE LOGIN MPEACOCK WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [NORTHWIND]
GO
CREATE USER MPEACOCK FOR LOGIN MPEACOCK
GO

GRANT INSERT ON ORDERS TO MPEACOCK
GO
GRANT DELETE ON ORDERS TO MPEACOCK
GO
GRANT UPDATE ON ORDERS TO MPEACOCK
GO

GRANT INSERT ON ORDERS TO JLEVERLING
GO
GRANT DELETE ON ORDERS TO JLEVERLING
GO
GRANT UPDATE ON ORDERS TO JLEVERLING
GO

/*
4.    STEVE BUCHANAN (SBUCHANAN) ES EL GERENTE DE VENTAS,
Y COMO TAL SE ENCARGA DE DARLE MANTENIMIENTO AL CATÁLOGO
DE PRODUCTOS DE LA EMPRESA.
*/

CREATE LOGIN SBUCHANAN WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [NORTHWIND]
GO
CREATE USER SBUCHANAN FOR LOGIN SBUCHANAN
GO

GRANT SELECT ON PRODUCTS TO SBUCHANAN
GO
GRANT UPDATE ON PRODUCTS TO SBUCHANAN

GO
GRANT INSERT ON PRODUCTS TO SBUCHANAN
GO
GRANT DELETE ON PRODUCTS TO SBUCHANAN
GO

/*
5.    MICHAEL SUYAMA (MSUYAMA), ROBERT KING (RKING),
Y ANNE DODSWORTH (ADODSWORTH) SON VENDEDORES LOCALES,
REPORTAN A STEVE BUCHANAN, Y DEBEN REGISTRAR SUS PEDIDOS EN EL SISTEMA.

UNA VEZ QUE HAN INGRESADO UN PEDIDO, PUEDEN CORREGIR ALGÚN DATO,
PERO NO PUEDEN ELIMINARLO. QUIEN SE ENCARGA DE ELIMINAR ALGÚN
PEDIDO DE LOS VENDEDORES LOCALES ES EL GERENTE DE VENTAS.
LOS VENDEDORES LOCALES PUEDEN REGISTRAR A SUS CLIENTES NUEVOS,
Y MODIFICAR LOS DATOS DE ALGÚN CLIENTE, PERO NO PUEDEN ELIMINARLOS
DEL SISTEMA.*/

CREATE LOGIN MSUYAMA WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER MSUYAMA FOR LOGIN MSUYAMA
GO

CREATE LOGIN RKING WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER RKING FOR LOGIN RKING
GO

CREATE LOGIN ADODSWORTH WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER ADODSWORTH FOR LOGIN ADODSWORTH
GO

GRANT UPDATE ON ORDERS TO MSUYAMA
GRANT UPDATE ON ORDERS TO ADODSWORTH
GRANT UPDATE ON ORDERS TO RKING
GO

GRANT DELETE ON ORDERS TO SBUCHANAN
GO



GRANT INSERT ON CUSTOMERS TO MSUYAMA
GRANT INSERT ON CUSTOMERS TO ADODSWORTH
GRANT INSERT ON CUSTOMERS TO RKING
GO

GRANT UPDATE ON CUSTOMERS TO MSUYAMA
GRANT UPDATE ON CUSTOMERS TO ADODSWORTH
GRANT UPDATE ON CUSTOMERS TO RKING
GO

/*
6.    LAURA CALLAHAN (LCALLAHAN) ES LA ADMINISTRADORA INTERNA Y
SE ENCARGA DE LA GESTIÓN DE LAS VENTAS EN LA TIENDA.
ELLA TAMBIÉN LE DA MANTENIMIENTO AL CATÁLOGO DE PRODUCTOS DE LA EMPRESA.
TAMBIÉN ES RESPONSABLE DEL MANTENIMIENTO DEL REGISTRO DE TRANSPORTISTAS.
*/  

CREATE LOGIN LCALLAHAN WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER LCALLAHAN FOR LOGIN LCALLAHAN
GO

GRANT SELECT ON PRODUCTS TO LCALLAHAN
GO
GRANT UPDATE ON PRODUCTS TO LCALLAHAN

GO
GRANT INSERT ON PRODUCTS TO LCALLAHAN
GO
GRANT DELETE ON PRODUCTS TO LCALLAHAN
GO

GRANT SELECT ON SHIPPERS TO LCALLAHAN
GO
GRANT UPDATE ON SHIPPERS TO LCALLAHAN

GO
GRANT INSERT ON SHIPPERS TO LCALLAHAN
GO
GRANT DELETE ON SHIPPERS TO LCALLAHAN
GO
/*
7.    URSULA PÉREZ (UPEREZ), GEORGE SMITH (GSMITH),
PETER VANNELS (PVANNELS), Y PETER MARTINEZ (PMARTINEZ)
SON VENDEDORES DE TIENDA.

ELLOS NECESITAN REGISTRAR SUS PEDIDOS EN EL SISTEMA.
TAMBIÉN PUEDEN ELIMINAR PEDIDOS Ó CORREGIR DATOS DEL PEDIDO.*/

CREATE LOGIN UPEREZ WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER UPEREZ FOR LOGIN UPEREZ
GO


GRANT UPDATE ON ORDERS TO UPEREZ
GRANT INSERT ON ORDERS TO UPEREZ
GRANT DELETE ON ORDERS TO UPEREZ
GO


CREATE LOGIN GSMITH WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER GSMITH FOR LOGIN GSMITH
GO


GRANT UPDATE ON ORDERS TO GSMITH
GRANT INSERT ON ORDERS TO GSMITH
GRANT DELETE ON ORDERS TO GSMITH
GO


CREATE LOGIN PVANNELS WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER PVANNELS FOR LOGIN PVANNELS
GO

GRANT UPDATE ON ORDERS TO PVANNELS
GRANT INSERT ON ORDERS TO PVANNELS
GRANT DELETE ON ORDERS TO PVANNELS
GO

CREATE LOGIN PMARTINEZ WITH PASSWORD=N'LEIRBAG1996@' MUST_CHANGE,
DEFAULT_DATABASE=[NORTHWIND],
DEFAULT_LANGUAGE=[ESPAÑOL],
 CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
CREATE USER PMARTINEZ FOR LOGIN PMARTINEZ
GO

GRANT UPDATE ON ORDERS TO PMARTINEZ
GRANT INSERT ON ORDERS TO PMARTINEZ
GRANT DELETE ON ORDERS TO PMARTINEZ
GO